[package]
name = "toy-pgmodeler-export-to-tsv-rs"
version = "0.1.0"
authors = ["Kobayasi, Hiroaki <buribullet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = "0.5.0"
